### ISSUE TITLE
Bug found in Freehisen app when undo button was clicked

### ISSUE THREAD

**Issue by darewealth** [knilch0r/freeshisen#13]
EXPECTED BEHAVIOR
The app was not expected to crash when undo button was clicked

ACTUAL BEHAVIOR
when the app was lauched, i clicked on option to access other options to choose from. clicking on undo button made the app to crash.

HOW TO REPRODUCE

Download 

Launch the app and open

Click on the options and click undo and note the bug

Device used: Gionee P5 mini

Operating system: Android version 5.1

App version: 0.6.4

Recording of the Bug

https://youtu.be/RcgMKBaw2U0

**Comment by knilch0r** [comment]
Thanks for your report!
The issue should be fixed in version 0.6.5 which is hitting the Play Store right now, can you check?
