### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by ghost** [knilch0r/freeshisen#4]
Please add license information to the readme or a seperate LICENSE or COPYING file. Original license was iirc GPLv2+

**Comment by knilch0r** [comment]
You're right, this should be part of the source as well.
Licensing up to now is only mentioned in https://github.com/knilch0r/freeshisen/blob/master/app/src/main/res/values/strings.xml#L10 (the aboutText string forming the content of the "about" dialog box).
I'll add that to the source repo in a minute.

**Comment by knilch0r** [comment]
should be solved now, please complain if I've missed something (I'm not a lawyer...)

**Comment by ghost** [comment]
Thanks for the quick reply and fix, should be good now... but I am not a lawyer myself :)
